### ISSUE TITLE
Unintentionally enabling automatic background updates for all plugins

### ISSUE THREAD

**Issue by mustardBees** [payfort/woocommerce-payfort#1]
The [following filter](https://github.com/payfort/woocommerce-payfort/blob/master/payfort_fort/woocommerce-fort.php#L13-15) also unintentionally enables auto updates for all plugins:

```php
add_filter('auto_update_plugin', '__return_true');
```

This issue also affects the "Payfort (Start)" plugin.

I would suggest dropping this line. In general, I would say the process of how updates are handled is something which should be left to the site owner/developer.

**Comment by DeyaZ88** [comment]
I will in next release, Thank you.
