### ISSUE TITLE
Payfort for joomla cms (virtuemart or hikashop)

### ISSUE THREAD

**Issue by mahmoodee** [payfort/woocommerce-payfort#11]
Hello ,
Please can you develop a plugin for joomla CMS
joomla have many ecommerce plugins like 
https://virtuemart.net/  which more popular than woocommerce
https://www.hikashop.com/ 
please we are waiting Payfort to be available to Joomla and Drupal

**Comment by mohannadsaleh** [comment]
currently we don't have ready plugin for joomla , we will do our best to implement all plugins that supports the majority of shopping carts frameworks in future .

Regards,
Mohannad
