### ISSUE TITLE
Payfort doesn't support you store currency at this time

### ISSUE THREAD

**Issue by MohamAladham** [payfort/woocommerce-payfort#13]
Hello,
I'm trying to install Payfort on my Woocommerce but I'm facing this problem and have been trying to solve it since days ago.

'Payfort doesn't support you store currency at this time'

although I have changed it to many different currencies such as Saudi Riyal...

Please check the following screenshot:

![image](https://user-images.githubusercontent.com/41272919/42739082-89b8f7d8-8898-11e8-842f-dd67484eddef.png)

**Comment by PayFortIntegration** [comment]
Hi MohamAladham,
Can you please email us on integration@payfort.com and share with us the issue you experience ? 
This is in order to assist you properly. 

Thanks
Esraa
