### ISSUE TITLE
is it working in WC 2.6.14?

### ISSUE THREAD

**Issue by telilbo** [payfort/woocommerce-payfort#15]
Hello, I'm Alan. 

before i try to use this plugin,  is it working in Woocommerce 2.6.x?
readme text file says tested Woocommerce 2.4.

Thanks
Alan

**Comment by DeyaZ88** [comment]
I've tested on version 2.7.x and its working just fine .

I think it will work for version 2.6.x too

**Comment by telilbo** [comment]
Thank you your response.
